version: 0.1
phases:
  pre_build:
    commands:
      - echo $REACT_APP_YAHOOFINANCE
      - echo $REACT_APP_OKTA_DOMAIN
      - echo Installing source YARN dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn run build

artifacts:
  base-directory: ./build
  files:
    - "**/*"

cache:
  paths:
    - "./node_modules/**/*"
