import React, { useEffect, useState, useContext } from "react";
import Store from "../../../store/Store";
import { IStock, IStockQuote } from "../../../interfaces";
import moment from "moment";
import DashCard from "../Containers/DashCardGraph";
import Grid from "@material-ui/core/Grid";
import Typography from "@material-ui/core/Typography";
import Box from "@material-ui/core/Box";

// TODO centralise logic at run time

// TODO move this to a utility function
const convertArrayToObject = (array, key) => {
  const initialValue = {};
  return array.reduce((obj, item) => {
    return {
      ...obj,
      [item[key]]: item,
    };
  }, initialValue);
};

const StockMoverShakers = (props) => {
  const { state } = useContext(Store);
  const { yahooFinanceApiOffStockCard } = state;
  const [dayGainers, setDayGainers] = useState<IStock>();
  const [dayLossers, setDayLossers] = useState<IStock>();
  const [dayMovers, setDayMovers] = useState<IStock>();
  const [quotes, setQuotes] = useState<IStockQuote>();
  const getYahooFinanceMovers = async () => {
    try {
      const resp = await fetch(
        "https://apidojo-yahoo-finance-v1.p.rapidapi.com/market/get-movers?region=US&lang=en",
        {
          method: "GET",
          headers: {
            "x-rapidapi-host": "apidojo-yahoo-finance-v1.p.rapidapi.com",
            "x-rapidapi-key":
              "403e8d2c3emshb2a6f056df380a9p121e13jsnce6b651b6124",
          },
        }
      );
      const data = await resp.json();
      return data;
    } catch (err) {
      console.error(err);
    }
  };
  const getYahooFinanceQuotes = async (props) => {
    console.log("props in Quotes", props);

    const listOfSymbols = props.quotes.join("%252C");
    console.log("listOfSymbols ", listOfSymbols);
    try {
      const resp = await fetch(
        `https://apidojo-yahoo-finance-v1.p.rapidapi.com/market/get-quotes?region=US&lang=en&symbols=${listOfSymbols}`,
        {
          method: "GET",
          headers: {
            "x-rapidapi-host": "apidojo-yahoo-finance-v1.p.rapidapi.com",
            "x-rapidapi-key":
              "403e8d2c3emshb2a6f056df380a9p121e13jsnce6b651b6124",
          },
        }
      );
      const data = await resp.json();
      console.log("getYahooFinanceQuotes ", data);
      return data;
    } catch (err) {
      console.error(err);
    }
  };
  useEffect(() => {
    const getDataAndDraw = async () => {
      const data = yahooFinanceApiOffStockCard
        ? fakedataMovers
        : await getYahooFinanceMovers();
      setDayGainers(data.finance.result[0]);
      setDayLossers(data.finance.result[1]);
      setDayMovers(data.finance.result[2]);
      console.log("gainers ", data);
      console.log(
        "symbols to pass ",
        data.finance.result[0].quotes.map((stock) => stock.symbol)
      );

      const dataQuotes = yahooFinanceApiOffStockCard
        ? fakeDataQuotes
        : await getYahooFinanceQuotes({
            quotes: data.finance.result[0].quotes.map((stock) => stock.symbol),
          });

      // convert the array of quotes into an object
      const dataQuotesObject = convertArrayToObject(
        dataQuotes.quoteResponse.result,
        "symbol"
      );

      setQuotes(dataQuotesObject);
    };
    getDataAndDraw();
  }, []);
  return (
    <div>
      {quotes ? (
        <>
          <Box p={2}>
            <Typography color="textPrimary" variant={"h2"}>
              {dayGainers?.title}
            </Typography>
          </Box>
          <Grid container spacing={1} justify="center" alignContent="center">
            {dayGainers?.quotes.map((moversQuote) => (
              <Grid item key={moversQuote.symbol} xs={12} sm={6} md={4} lg={3}>
                <DashCard
                  metricName={
                    quotes[moversQuote.symbol].longName +
                    " (" +
                    moversQuote.symbol +
                    ")"
                  }
                  curretMetricValue={quotes[
                    moversQuote.symbol
                  ].regularMarketPrice
                    .toFixed(2)
                    .toString()}
                  units={"USD"}
                  metricChange={quotes[moversQuote.symbol].regularMarketChange
                    .toFixed(2)
                    .toString()}
                  metricPercentageChange={
                    quotes[moversQuote.symbol].regularMarketChangePercent
                      .toFixed(1)
                      .toString() + "%"
                  }
                  timeUpdated={
                    "Last updated: " +
                    moment(quotes[moversQuote.symbol].regularMarketTime).format(
                      "DD MMM YY"
                    )
                  }
                />
              </Grid>
            ))}
          </Grid>

          {/* <Typography color="textPrimary" variant={"h2"}>{dayLossers.title}</Typography> */}
          {/* TODO need to add in DEV data for losers */}

          {/* <Grid container spacing={1} justify="center" alignContent="center">
            {dayLossers.quotes.map(moversQuote => (
              <Grid item key={moversQuote.symbol} xs={12} sm={6} md={4} lg={3}>
                <DashCard
                  metricName={
                    quotes[moversQuote.symbol].longName +
                    "(" +
                    moversQuote.symbol +
                    ")"
                  }
                  curretMetricValue={quotes[
                    moversQuote.symbol
                  ].regularMarketPrice
                    .toFixed(2)
                    .toString()}
                  units={"USD"}
                  metricChange={quotes[moversQuote.symbol].regularMarketChange
                    .toFixed(2)
                    .toString()}
                  metricPercentageChange={
                    quotes[moversQuote.symbol].regularMarketChangePercent
                      .toFixed(1)
                      .toString() + "%"
                  }
                  timeUpdated={
                    "Last updated: " +
                    moment(quotes[moversQuote.symbol].regularMarketTime).format(
                      "DD MMM YY"
                    )
                  }
                />
              </Grid>
            ))}
          </Grid> */}
        </>
      ) : (
        <div />
      )}
    </div>
  );
};

export default StockMoverShakers;

const fakedataMovers = {
  finance: {
    result: [
      {
        id: "ec5bebb9-b7b2-4474-9e5c-3e258b61cbe6",
        title: "Day Gainers - US",
        description:
          "Stocks ordered in descending order by price percent change greater than 3% with respect to the previous close",
        canonicalName: "DAY_GAINERS",
        criteriaMeta: {
          size: 6,
          offset: 0,
          sortField: "percentchange",
          sortType: "DESC",
          quoteType: "EQUITY",
          topOperator: "AND",
          criteria: [
            {
              field: "percentchange",
              operators: ["GT"],
              values: [3],
              labelsSelected: [],
            },
            {
              field: "region",
              operators: ["EQ"],
              values: [],
              labelsSelected: [53],
            },
            {
              field: "intradaymarketcap",
              operators: ["EQ"],
              values: [],
              labelsSelected: [1, 2, 3],
            },
            {
              field: "dayvolume",
              operators: ["GT"],
              values: [15000],
              labelsSelected: [],
            },
          ],
        },
        rawCriteria:
          '{"offset":0,"size":6,"sortField":"percentchange","sortType":"DESC","quoteType":"EQUITY","query":{"operator":"AND","operands":[{"operator":"GT","operands":["percentchange",3.0]},{"operator":"eq","operands":["region","us"]},{"operator":"or","operands":[{"operator":"BTWN","operands":["intradaymarketcap",2000000000,10000000000]},{"operator":"BTWN","operands":["intradaymarketcap",10000000000,100000000000]},{"operator":"GT","operands":["intradaymarketcap",100000000000]}]},{"operator":"gt","operands":["dayvolume",15000]}]}}',
        start: 0,
        count: 6,
        total: 32,
        quotes: [
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NMS",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NasdaqGS",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "EHTH",
          },
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NMS",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NasdaqGS",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "VIR",
          },
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NMS",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NasdaqGS",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "ADPT",
          },
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NMS",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NasdaqGS",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "TEAM",
          },
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NMS",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NasdaqGS",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "BLDP",
          },
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NMS",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NasdaqGS",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "INTC",
          },
        ],
        predefinedScr: true,
        versionId: 6,
      },
      {
        id: "8ecefa87-a8b0-434a-9b39-e061a0baef9b",
        title: "Day Losers - US",
        description:
          "Stocks ordered in ascending order by price percent change with respect to the previous close",
        canonicalName: "DAY_LOSERS",
        criteriaMeta: {
          size: 6,
          offset: 0,
          sortField: "percentchange",
          sortType: "ASC",
          quoteType: "EQUITY",
          topOperator: "AND",
          criteria: [
            {
              field: "percentchange",
              operators: ["LT"],
              values: [-2.5],
              labelsSelected: [],
            },
            {
              field: "region",
              operators: ["EQ"],
              values: [],
              labelsSelected: [53],
            },
            {
              field: "intradaymarketcap",
              operators: ["EQ"],
              values: [],
              labelsSelected: [1, 2, 3],
            },
            {
              field: "dayvolume",
              operators: ["GT"],
              values: [20000],
              labelsSelected: [],
            },
          ],
        },
        rawCriteria:
          '{"offset":0,"size":6,"sortField":"percentchange","sortType":"ASC","quoteType":"EQUITY","query":{"operator":"AND","operands":[{"operator":"LT","operands":["percentchange",-2.5]},{"operator":"eq","operands":["region","us"]},{"operator":"or","operands":[{"operator":"BTWN","operands":["intradaymarketcap",2000000000,10000000000]},{"operator":"BTWN","operands":["intradaymarketcap",10000000000,100000000000]},{"operator":"GT","operands":["intradaymarketcap",100000000000]}]},{"operator":"gt","operands":["dayvolume",20000]}]}}',
        start: 0,
        count: 6,
        total: 291,
        quotes: [
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NMS",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NasdaqGS",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "EPZM",
          },
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NYQ",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NYSE",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "DFS",
          },
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NYQ",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NYSE",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "SPCE",
          },
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NYQ",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NYSE",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "SYF",
          },
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NMS",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NasdaqGS",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "CRON",
          },
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: false,
            exchange: "PNK",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "Other OTC",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "NKRKY",
          },
        ],
        predefinedScr: true,
        versionId: 4,
      },
      {
        id: "437465ef-980e-4d8c-a860-de7cbfbab373",
        title: "Most Actives - US",
        description:
          "Stocks ordered in descending order by intraday trade volume",
        canonicalName: "MOST_ACTIVES",
        criteriaMeta: {
          size: 6,
          offset: 0,
          sortField: "dayvolume",
          sortType: "DESC",
          quoteType: "EQUITY",
          topOperator: "AND",
          criteria: [
            {
              field: "region",
              operators: ["EQ"],
              values: [],
              labelsSelected: [53],
            },
            {
              field: "intradaymarketcap",
              operators: ["EQ"],
              values: [],
              labelsSelected: [1, 2, 3],
            },
            {
              field: "dayvolume",
              operators: ["GT"],
              values: [5000000],
              labelsSelected: [],
            },
          ],
        },
        rawCriteria:
          '{"offset":0,"size":6,"sortField":"dayvolume","sortType":"DESC","quoteType":"EQUITY","query":{"operator":"AND","operands":[{"operator":"eq","operands":["region","us"]},{"operator":"or","operands":[{"operator":"BTWN","operands":["intradaymarketcap",2000000000,10000000000]},{"operator":"BTWN","operands":["intradaymarketcap",10000000000,100000000000]},{"operator":"GT","operands":["intradaymarketcap",100000000000]}]},{"operator":"gt","operands":["dayvolume",5000000]}]}}',
        start: 0,
        count: 6,
        total: 187,
        quotes: [
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NMS",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NasdaqGS",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "INTC",
          },
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NMS",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NasdaqGS",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "AMD",
          },
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NYQ",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NYSE",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "F",
          },
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NYQ",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NYSE",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "NIO",
          },
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NYQ",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NYSE",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "GE",
          },
          {
            language: "en",
            region: "US",
            quoteType: "EQUITY",
            triggerable: true,
            exchange: "NYQ",
            sourceInterval: 15,
            exchangeTimezoneName: "America/New_York",
            exchangeTimezoneShortName: "EST",
            gmtOffSetMilliseconds: -18000000,
            esgPopulated: false,
            tradeable: true,
            exchangeDataDelayedBy: 0,
            market: "us_market",
            fullExchangeName: "NYSE",
            marketState: "CLOSED",
            priceHint: 2,
            symbol: "BAC",
          },
        ],
        predefinedScr: true,
        versionId: 6,
      },
    ],
    error: null,
  },
};

const fakeDataQuotes = {
  quoteResponse: {
    result: [
      {
        language: "en-US",
        region: "US",
        quoteType: "EQUITY",
        triggerable: true,
        quoteSourceName: "Delayed Quote",
        currency: "USD",
        esgPopulated: false,
        tradeable: true,
        exchangeDataDelayedBy: 0,
        shortName: "eHealth, Inc.",
        priceHint: 2,
        targetPriceMean: 124.73,
        postMarketChangePercent: 0,
        postMarketTime: 1579902669,
        postMarketPrice: 123.26,
        postMarketChange: 0,
        regularMarketChangePercent: 26.902094,
        regularMarketDayRange: "110.92 - 130.0",
        regularMarketPreviousClose: 97.13,
        bid: 122.63,
        ask: 124.75,
        bidSize: 32,
        askSize: 12,
        messageBoardId: "finmb_27933",
        fullExchangeName: "NasdaqGS",
        longName: "eHealth, Inc.",
        averageDailyVolume3Month: 647573,
        beta: 1.147485,
        fiftyTwoWeekLowChange: 74.07001,
        fiftyTwoWeekLowChangePercent: 1.505794,
        fiftyTwoWeekRange: "49.19 - 130.0",
        fiftyTwoWeekHighChange: -6.739998,
        fiftyTwoWeekHighChangePercent: -0.05184614,
        fiftyTwoWeekLow: 49.19,
        fiftyTwoWeekHigh: 130,
        earningsTimestamp: 1571933406,
        earningsTimestampStart: 1582109940,
        earningsTimestampEnd: 1582545600,
        trailingPE: 700.34094,
        dividendsPerShare: 0,
        epsTrailingTwelveMonths: 0.176,
        sharesOutstanding: 23098200,
        marketCap: 2847084288,
        sourceInterval: 15,
        exchangeTimezoneName: "America/New_York",
        exchangeTimezoneShortName: "EST",
        pageViews: {
          shortTermTrend: "UP",
          midTermTrend: "UP",
          longTermTrend: "UP",
        },
        gmtOffSetMilliseconds: -18000000,
        components: [
          "^NQDMXKRAUDN",
          "^XCQ",
          "^NQDMXKRSCEURN",
          "^NQDMXKRSCCAD",
          "^NQDMXKRSCN",
          "^NQUSSVN",
          "^NQDMXKREURN",
          "^NQDMXKRAUD",
          "^NQDMXKRSCJPYN",
          "^NQDMXKRSCCADN",
          "^NQDMXKRJPY",
          "^NQGS",
          "^NQDMXKRN",
          "^NQDMXKRSCAUD",
          "^NQDMXKRGBP",
          "^NQUSSV",
          "^NQDMXKRJPYN",
          "^NQDMXKRSCJPY",
          "^NQDMXKRSCGBPN",
          "^IXIC",
          "^INSR",
          "^NQDMXKRCADN",
          "^NQDMXKREUR",
          "^NQDMXKRCAD",
          "^NQDMXKRSCAUDN",
          "^NQDMXKRSCEUR",
          "^NQDMXKR",
          "^NQDMXKRSCGBP",
          "^NQDMXKRGBPN",
          "^NQDMXKRSC",
        ],
        regularMarketPrice: 123.26,
        regularMarketTime: 1579899601,
        regularMarketChange: 26.130005,
        regularMarketOpen: 115.44,
        regularMarketDayHigh: 130,
        regularMarketDayLow: 110.92,
        regularMarketVolume: 4841342,
        market: "us_market",
        marketState: "CLOSED",
        exchange: "NMS",
        symbol: "EHTH",
      },
      {
        language: "en-US",
        region: "US",
        quoteType: "EQUITY",
        triggerable: true,
        quoteSourceName: "Delayed Quote",
        currency: "USD",
        esgPopulated: false,
        tradeable: true,
        exchangeDataDelayedBy: 0,
        shortName: "Vir Biotechnology, Inc.",
        priceHint: 2,
        targetPriceMean: 26,
        postMarketChangePercent: 7.7192936,
        postMarketTime: 1579912114,
        postMarketPrice: 21.49,
        postMarketChange: 1.539999,
        regularMarketChangePercent: 17.491173,
        regularMarketDayRange: "17.0 - 20.16",
        regularMarketPreviousClose: 16.98,
        bid: 20.76,
        ask: 20.85,
        bidSize: 11,
        askSize: 10,
        messageBoardId: "finmb_419881198",
        fullExchangeName: "NasdaqGS",
        longName: "Vir Biotechnology, Inc.",
        averageDailyVolume3Month: 141870,
        fiftyTwoWeekLowChange: 8.300001,
        fiftyTwoWeekLowChangePercent: 0.71244645,
        fiftyTwoWeekRange: "11.65 - 20.16",
        fiftyTwoWeekHighChange: -0.20999908,
        fiftyTwoWeekHighChangePercent: -0.010416621,
        fiftyTwoWeekLow: 11.65,
        fiftyTwoWeekHigh: 20.16,
        dividendsPerShare: 0,
        epsTrailingTwelveMonths: -14.642,
        sharesOutstanding: 109679000,
        marketCap: 2188096256,
        sourceInterval: 15,
        exchangeTimezoneName: "America/New_York",
        exchangeTimezoneShortName: "EST",
        pageViews: {
          shortTermTrend: "UP",
          midTermTrend: "UP",
          longTermTrend: "UP",
        },
        gmtOffSetMilliseconds: -18000000,
        regularMarketPrice: 19.95,
        regularMarketTime: 1579899601,
        regularMarketChange: 2.9700012,
        regularMarketOpen: 17.42,
        regularMarketDayHigh: 20.16,
        regularMarketDayLow: 17,
        regularMarketVolume: 440118,
        market: "us_market",
        marketState: "CLOSED",
        exchange: "NMS",
        symbol: "VIR",
      },
      {
        language: "en-US",
        region: "US",
        quoteType: "EQUITY",
        triggerable: true,
        quoteSourceName: "Delayed Quote",
        currency: "USD",
        esgPopulated: false,
        tradeable: true,
        exchangeDataDelayedBy: 0,
        shortName: "Adaptive Biotechnologies Corpor",
        priceHint: 2,
        targetPriceMean: 44.75,
        postMarketChangePercent: 1.1129302,
        postMarketTime: 1579909240,
        postMarketPrice: 30.89,
        postMarketChange: 0.34000015,
        regularMarketChangePercent: 13.780255,
        regularMarketDayRange: "27.7 - 31.0",
        regularMarketPreviousClose: 26.85,
        bid: 30.3,
        ask: 30.88,
        bidSize: 13,
        askSize: 13,
        messageBoardId: "finmb_100147173",
        fullExchangeName: "NasdaqGS",
        longName: "Adaptive Biotechnologies Corporation",
        averageDailyVolume3Month: 993286,
        fiftyTwoWeekLowChange: 6.5,
        fiftyTwoWeekLowChangePercent: 0.2702703,
        fiftyTwoWeekRange: "24.05 - 55.12",
        fiftyTwoWeekHighChange: -24.57,
        fiftyTwoWeekHighChangePercent: -0.4457547,
        fiftyTwoWeekLow: 24.05,
        fiftyTwoWeekHigh: 55.12,
        earningsTimestamp: 1573574700,
        earningsTimestampStart: 1573574700,
        earningsTimestampEnd: 1573574700,
        dividendsPerShare: 0,
        epsTrailingTwelveMonths: -1.507,
        sharesOutstanding: 124339000,
        marketCap: 3798556416,
        sourceInterval: 15,
        exchangeTimezoneName: "America/New_York",
        exchangeTimezoneShortName: "EST",
        pageViews: {
          shortTermTrend: "UP",
          midTermTrend: "UP",
          longTermTrend: "UP",
        },
        gmtOffSetMilliseconds: -18000000,
        regularMarketPrice: 30.55,
        regularMarketTime: 1579899601,
        regularMarketChange: 3.6999989,
        regularMarketOpen: 28.02,
        regularMarketDayHigh: 31,
        regularMarketDayLow: 27.7,
        regularMarketVolume: 12075601,
        market: "us_market",
        marketState: "CLOSED",
        exchange: "NMS",
        symbol: "ADPT",
      },
      {
        language: "en-US",
        region: "US",
        quoteType: "EQUITY",
        triggerable: true,
        quoteSourceName: "Nasdaq Real Time Price",
        currency: "USD",
        esgPopulated: false,
        tradeable: true,
        exchangeDataDelayedBy: 0,
        shortName: "Atlassian Corporation Plc",
        priceHint: 2,
        targetPriceMean: 152.38,
        postMarketChangePercent: -0.299739,
        postMarketTime: 1579913707,
        postMarketPrice: 146.35,
        postMarketChange: -0.439987,
        regularMarketChangePercent: 10.667969,
        regularMarketDayRange: "140.98 - 150.59",
        regularMarketPreviousClose: 132.64,
        bid: 146.37,
        ask: 146.57,
        bidSize: 10,
        askSize: 10,
        messageBoardId: "finmb_253891410",
        fullExchangeName: "NasdaqGS",
        longName: "Atlassian Corporation Plc",
        averageDailyVolume3Month: 1480024,
        beta: 1.235779,
        fiftyTwoWeekLowChange: 54.368996,
        fiftyTwoWeekLowChangePercent: 0.5882754,
        fiftyTwoWeekRange: "92.421 - 150.71",
        fiftyTwoWeekHighChange: -3.9200134,
        fiftyTwoWeekHighChangePercent: -0.026010307,
        fiftyTwoWeekLow: 92.421,
        fiftyTwoWeekHigh: 150.71,
        earningsTimestamp: 1579795380,
        earningsTimestampStart: 1586948340,
        earningsTimestampEnd: 1587384000,
        dividendsPerShare: 0,
        epsTrailingTwelveMonths: -1.022,
        sharesOutstanding: 120672000,
        marketCap: 35839655936,
        sourceInterval: 15,
        exchangeTimezoneName: "America/New_York",
        exchangeTimezoneShortName: "EST",
        pageViews: {
          shortTermTrend: "UP",
          midTermTrend: "UP",
          longTermTrend: "UP",
        },
        gmtOffSetMilliseconds: -18000000,
        regularMarketPrice: 146.79,
        regularMarketTime: 1579899601,
        regularMarketChange: 14.149994,
        regularMarketOpen: 145,
        regularMarketDayHigh: 150.59,
        regularMarketDayLow: 140.98,
        regularMarketVolume: 8033676,
        market: "us_market",
        marketState: "CLOSED",
        exchange: "NMS",
        symbol: "TEAM",
      },
      {
        language: "en-US",
        region: "US",
        quoteType: "EQUITY",
        triggerable: true,
        quoteSourceName: "Nasdaq Real Time Price",
        currency: "USD",
        esgPopulated: false,
        tradeable: true,
        exchangeDataDelayedBy: 0,
        shortName: "Ballard Power Systems, Inc.",
        priceHint: 2,
        targetPriceMean: 5.4,
        postMarketChangePercent: 0.515466,
        postMarketTime: 1579913900,
        postMarketPrice: 9.75,
        postMarketChange: 0.0500002,
        regularMarketChangePercent: 8.379889,
        regularMarketDayRange: "9.27 - 9.84",
        regularMarketPreviousClose: 8.95,
        bid: 9.75,
        ask: 9.8,
        bidSize: 32,
        askSize: 8,
        messageBoardId: "finmb_25395",
        fullExchangeName: "NasdaqGS",
        longName: "Ballard Power Systems Inc.",
        averageDailyVolume3Month: 2439624,
        beta: 2.627543,
        fiftyTwoWeekLowChange: 6.85,
        fiftyTwoWeekLowChangePercent: 2.403509,
        fiftyTwoWeekRange: "2.85 - 12.13",
        fiftyTwoWeekHighChange: -2.4300003,
        fiftyTwoWeekHighChangePercent: -0.20032978,
        fiftyTwoWeekLow: 2.85,
        fiftyTwoWeekHigh: 12.13,
        dividendsPerShare: 0,
        epsTrailingTwelveMonths: -0.178,
        sharesOutstanding: 233511008,
        marketCap: 2256588544,
        sourceInterval: 15,
        exchangeTimezoneName: "America/New_York",
        exchangeTimezoneShortName: "EST",
        pageViews: {
          shortTermTrend: "DOWN",
          midTermTrend: "UP",
          longTermTrend: "UP",
        },
        gmtOffSetMilliseconds: -18000000,
        components: [
          "^QGREEN",
          "^GRNEXUS",
          "^XCQ",
          "^GRNREG",
          "^NQGM",
          "^GRNCLNFO",
          "^IXIC",
          "^GRNFUEL",
          "^CELS",
          "^INDS",
          "^GRNFCEXUS",
        ],
        regularMarketPrice: 9.7,
        regularMarketTime: 1579899601,
        regularMarketChange: 0.75,
        regularMarketOpen: 9.66,
        regularMarketDayHigh: 9.84,
        regularMarketDayLow: 9.27,
        regularMarketVolume: 4444252,
        market: "us_market",
        marketState: "CLOSED",
        exchange: "NMS",
        symbol: "BLDP",
      },
      {
        language: "en-US",
        region: "US",
        quoteType: "EQUITY",
        triggerable: true,
        quoteSourceName: "Delayed Quote",
        currency: "USD",
        esgPopulated: false,
        tradeable: true,
        exchangeDataDelayedBy: 0,
        shortName: "Intel Corporation",
        priceHint: 2,
        targetPriceMean: 58.28,
        postMarketChangePercent: -0.24828124,
        postMarketTime: 1579913983,
        postMarketPrice: 68.3,
        postMarketChange: -0.16999817,
        regularMarketChangePercent: 8.133294,
        regularMarketDayRange: "66.46 - 69.28",
        regularMarketPreviousClose: 63.32,
        bid: 68.3,
        ask: 68.36,
        bidSize: 9,
        askSize: 12,
        messageBoardId: "finmb_21127",
        fullExchangeName: "NasdaqGS",
        longName: "Intel Corporation",
        averageDailyVolume3Month: 20244785,
        beta: 0.910485,
        fiftyTwoWeekLowChange: 25.61,
        fiftyTwoWeekLowChangePercent: 0.59752685,
        fiftyTwoWeekRange: "42.86 - 69.29",
        fiftyTwoWeekHighChange: -0.8199997,
        fiftyTwoWeekHighChangePercent: -0.011834315,
        fiftyTwoWeekLow: 42.86,
        fiftyTwoWeekHigh: 69.29,
        earningsTimestamp: 1587672000,
        earningsTimestampStart: 1587672000,
        earningsTimestampEnd: 1587672000,
        trailingPE: 14.537155,
        dividendsPerShare: 1.25,
        dividendRate: 1.26,
        dividendYield: 1.99,
        epsTrailingTwelveMonths: 4.71,
        sharesOutstanding: 4350000128,
        marketCap: 297844506624,
        sourceInterval: 15,
        exchangeTimezoneName: "America/New_York",
        exchangeTimezoneShortName: "EST",
        pageViews: {
          shortTermTrend: "UP",
          midTermTrend: "UP",
          longTermTrend: "UP",
        },
        gmtOffSetMilliseconds: -18000000,
        components: [
          "^NQDMXJPLMAUD",
          "^NQUSBLM",
          "^QIV",
          "^NQUSB9576LMGBPN",
          "^NQUSB9576LM",
          "^NQGS",
          "^NQNALMEURN",
          "^NQSSSEN",
          "^NQUSB9000LMJPYN",
          "^NQUSBLMCAD",
          "^NQUSB9000LMEURN",
          "^NQDMXKRJPYN",
          "^NQDMXKRLMAUDN",
          "^NQNA9000LMGBPN",
          "^NQUSB9570LMJPY",
          "^NQDMXJPLMAUDN",
          "^NQDMXKRLMAUD",
          "^NQUSBLMJPY",
          "^NDXCHF",
          "^NQNA9000LMEUR",
          "^NQNA9000LMCAD",
          "^NQGXGBLMN",
          "^NQUS500LCVN",
          "^NQDMXKRLCJPY",
          "^NQUSB9000LMEUR",
          "^NQDXUSLCEUR",
          "^INTSY",
          "^NQUSB9000LMCAD",
          "^NQDM9000LMJPY",
          "^NQG9000LMCADN",
          "^NQDMXKRAUD",
          "^NQDMXKRLMGBPN",
          "^NQDXUSMLTCVN",
          "^NQGXGBLMGBPN",
          "^NQDM9000LMEURN",
          "^NQGXJPLMJPYN",
          "^NQNALMCADN",
          "^NQUSBLMEUR",
          "^NQG9000LMGBP",
          "^NQDM9000LMJPYN",
          "^NQNALMJPY",
          "^MSH",
          "^NDX",
          "^NQGXGBLMJPY",
          "^QCRD",
          "^NQUSB9570LMGBPN",
          "^SOX",
          "^IXCO",
          "^NQGXJPLMJPY",
          "^NQDMXKR",
          "^NQDMXGBLMCADN",
          "^NQUSB9000LMJPY",
          "^NQDMXKRLCN",
          "^NQGXGBLMEURN",
          "^NQGXJPLMCAD",
          "^NQGXJPLMEUR",
          "^XNDXNNRCHF",
          "^NQDMXJPLMGBPN",
          "^NQUSLV",
          "^NQDMXJPLMN",
          "^NQDM9000LMAUD",
          "^NQDMXKRLCJPYN",
          "^NQDMXKRLMCADN",
          "^NQDMXKRLCEUR",
          "^NQSSSE",
          "^NQUSB9000LMN",
          "^NQDXUSLC",
          "^NQUSB9570LMAUDN",
          "^NQGXGBLMJPYN",
          "^NQG9000LMJPYN",
          "^NQUSBLMEURN",
          "^NQDMXKRJPY",
          "^NQDMXKRLCCAD",
          "^NQUSB9570LM",
          "^NQDMXKRLCEURN",
          "^NQG9000LMAUD",
          "^NQUSB9576LMGBP",
          "^NQGXJPLMGBPN",
          "^QMI",
          "^NQUSB9000LMCADN",
          "^IXIC",
          "^NQNALM",
          "^NQUS500LC",
          "^NQDMXGBLMJPY",
          "^NQUSMLTCV",
          "^NQNALMAUD",
          "^NQNA9000LMN",
          "^NQVMVUS",
          "^NQDXUSLCN",
          "^NQGXGBLMAUD",
          "^NQDXUSLCV",
          "^NQUSBLMN",
          "^NQDMXJPLMGBP",
          "^NQFGSL",
          "^NQUSB9570LMCADN",
          "^NQDMXKRLMEUR",
          "^MNX1",
          "^NQNALMAUDN",
          "^GMB",
          "^NQG9000LMEURN",
          "^NQUSB9576LMJPYN",
          "^NQDM9000LMCADN",
          "^NQDMXKRLMCAD",
          "^NQDMXGBLM",
          "^NQUSB9570LMAUD",
          "^NQUSB9576LMAUD",
          "^NQNA9000LMGBP",
          "^NQDMXGBLMJPYN",
          "^NQG9000LMN",
          "^NQDMXKRLMJPY",
          "^NQUSBLMJPYN",
          "^NQDM9000LMN",
          "^NQDMXGBLMCAD",
          "^XNDXNNRGBP",
          "^NQDMXGBLMEURN",
          "^NQDMXKRGBPN",
          "^NQDMXGBLMEUR",
          "^XNDXNNR",
          "^NQDMXKRAUDN",
          "^NQDMXKRLMJPYN",
          "^NQUSBLMCADN",
          "^NQDMXGBLMN",
          "^NQNALMGBPN",
          "^NQGXGBLMCADN",
          "^RSDNTR",
          "^NQDMXKRLCCADN",
          "^NQGXJPLMCADN",
          "^NQGXJPLM",
          "^NQUSB9576LMEURN",
          "^NQNA9000LMAUD",
          "^NQUSB9570LMGBP",
          "^NQUSBLMGBP",
          "^RSD",
          "^NQNALMN",
          "^NQUSB9000LMAUD",
          "^NQNA9000LM",
          "^NQUSB9570LMEURN",
          "^SX",
          "^NQGXJPLMAUDN",
          "^NQUSLVN",
          "^NQCAPST",
          "^NQ96DIVUS",
          "^DJI",
          "^NQDMXKRLCGBP",
          "^NQDMXKRLM",
          "^NQDM9000LMGBP",
          "^NQDMXKRLC",
          "^NQNALMGBP",
          "^NDXEUR",
          "^NDXHKD",
          "^NQDMXJPLMJPYN",
          "^NQG9000LMEUR",
          "^NQGXGBLM",
          "^NQG9000LMCAD",
          "^NQDMXKRN",
          "^NQUSB9570LMN",
          "^NQUSMLTCVN",
          "^XQC",
          "^NQCRDN",
          "^NQDMXJPLMEURN",
          "^NQG9000LMJPY",
          "^NDXCAD",
          "^NQNA9000LMJPYN",
          "^NQDMXJPLM",
          "^NQDMXKREUR",
          "^NQGXJPLMGBP",
          "^NQDM9000LMAUDN",
          "^NQDMXKRLMEURN",
          "^NQUSBLMAUD",
          "^NQGXGBLMGBP",
          "^NQDMXKRCAD",
          "^NQNA9000LMEURN",
          "^XQO",
          "^DJA",
          "^NQDXUSMLTCV",
          "^NQUSB9000LMAUDN",
          "^NQUSB9000LMGBP",
          "^NQDXUSLCEURN",
          "^GMBNTR",
          "^NQNA9000LMAUDN",
          "^NQG9000LMAUDN",
          "^NQUSB9576LMN",
          "^NQDMXKRLCAUD",
          "^XCQ",
          "^NQDXUSMEGAN",
          "^NQNALMCAD",
          "^XCI",
          "^NQGXJPLMEURN",
          "^NQDM9000LM",
          "^NQDXUSLCGBP",
          "^NQGXJPLMN",
          "^NQNALMEUR",
          "^NDXGBP",
          "^NQGXGBLMEUR",
          "^NQUSB9576LMJPY",
          "^NQDMXKRGBP",
          "^NQDM9000LMEUR",
          "^XNDXNNRHKD",
          "^NQDM9000LMCAD",
          "^NQDMXGBLMGBPN",
          "^XNDXNNREUR",
          "^NQCRD",
          "^NQDMXKRCADN",
          "^NQGXGBLMCAD",
          "^NQDMXGBLMGBP",
          "^NQDMXKRLCAUDN",
          "^NQUSB9576LMCADN",
          "^XNDXNNRCAD",
          "^NQDM9000LMGBPN",
          "^NQDXUSLCGBPN",
          "^NQUSB9570LMJPYN",
          "^NQG9000LM",
          "^NQUSBLMGBPN",
          "^NQDMXKRLMN",
          "^NQFGSLN",
          "^NQGXJPLMAUD",
          "^NQDMXGBLMAUDN",
          "^NDXT",
          "^NQUSB9000LM",
          "^NQDMXJPLMJPY",
          "^NQDMXKRLCGBPN",
          "^NQVMVUSN",
          "^NDXE",
          "^NQDMXKREURN",
          "^NQNALMJPYN",
          "^NQUSB9000LMGBPN",
          "^NQUSB9576LMCAD",
          "^NQG9000LMGBPN",
          "^NQUSB9576LMEUR",
          "^NQDMXJPLMCADN",
          "^NQDVRIS",
          "^NQUSB9570LMCAD",
          "^NQUSB9570LMEUR",
          "^NQDMXGBLMAUD",
          "^NQUSBLMAUDN",
          "^NQNA9000LMJPY",
          "^NQDMXJPLMCAD",
          "^NQDMXJPLMEUR",
          "^NQDXUSMEGA",
          "^NQDMXKRLMGBP",
          "^NQDXUSLCVN",
          "^NQGXGBLMAUDN",
          "^NQUSB9576LMAUDN",
          "^NQUS500LCN",
          "^AXJ",
          "^NQNA9000LMCADN",
          "^NQUS500LCV",
        ],
        regularMarketPrice: 68.47,
        regularMarketTime: 1579899601,
        regularMarketChange: 5.1500015,
        regularMarketOpen: 66.57,
        regularMarketDayHigh: 69.28,
        regularMarketDayLow: 66.46,
        regularMarketVolume: 84711037,
        market: "us_market",
        marketState: "CLOSED",
        exchange: "NMS",
        symbol: "INTC",
      },
    ],
    error: null,
  },
};
